[2023-09-04T10:03:12.793-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Investimento_api.Insert_Postgres manual__2023-09-04T13:02:52.250492+00:00 [queued]>
[2023-09-04T10:03:12.802-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Investimento_api.Insert_Postgres manual__2023-09-04T13:02:52.250492+00:00 [queued]>
[2023-09-04T10:03:12.802-0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-04T10:03:12.818-0300] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): Insert_Postgres> on 2023-09-04 13:02:52.250492+00:00
[2023-09-04T10:03:12.822-0300] {standard_task_runner.py:57} INFO - Started process 13874 to run task
[2023-09-04T10:03:12.826-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Investimento_api', 'Insert_Postgres', 'manual__2023-09-04T13:02:52.250492+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpj2wu0k7z']
[2023-09-04T10:03:12.828-0300] {standard_task_runner.py:85} INFO - Job 53: Subtask Insert_Postgres
[2023-09-04T10:03:12.907-0300] {task_command.py:410} INFO - Running <TaskInstance: Investimento_api.Insert_Postgres manual__2023-09-04T13:02:52.250492+00:00 [running]> on host VMEnricolm.myguest.virtualbox.org
[2023-09-04T10:03:13.037-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Investimento_api' AIRFLOW_CTX_TASK_ID='Insert_Postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T13:02:52.250492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-04T13:02:52.250492+00:00'
[2023-09-04T10:03:13.038-0300] {sql.py:265} INFO - Executing: COPY Apple_table FROM '/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-09-04/data.csv' CSV HEADER;
[2023-09-04T10:03:13.059-0300] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-09-04T10:03:13.082-0300] {logging_mixin.py:150} WARNING - /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/models/connection.py:372 AirflowProviderDeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2023-09-04T10:03:13.099-0300] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-09-04T10:03:13.116-0300] {sql.py:375} INFO - Running statement: COPY Apple_table FROM '/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-09-04/data.csv' CSV HEADER;, parameters: None
[2023-09-04T10:03:13.117-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 271, in execute
    output = hook.run(
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-09-04/data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-09-04T10:03:13.138-0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=Investimento_api, task_id=Insert_Postgres, execution_date=20230904T130252, start_date=20230904T130312, end_date=20230904T130313
[2023-09-04T10:03:13.153-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task Insert_Postgres (could not open file "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-09-04/data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 13874)
[2023-09-04T10:03:13.171-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-04T10:03:13.198-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
