[2023-09-04T10:02:16.548-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Investimento_api.Insert_Postgres manual__2023-09-04T13:01:48.178412+00:00 [queued]>
[2023-09-04T10:02:16.557-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Investimento_api.Insert_Postgres manual__2023-09-04T13:01:48.178412+00:00 [queued]>
[2023-09-04T10:02:16.557-0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-04T10:02:16.594-0300] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): Insert_Postgres> on 2023-09-04 13:01:48.178412+00:00
[2023-09-04T10:02:16.598-0300] {standard_task_runner.py:57} INFO - Started process 13541 to run task
[2023-09-04T10:02:16.601-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Investimento_api', 'Insert_Postgres', 'manual__2023-09-04T13:01:48.178412+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsqxsn1ku']
[2023-09-04T10:02:16.604-0300] {standard_task_runner.py:85} INFO - Job 51: Subtask Insert_Postgres
[2023-09-04T10:02:16.722-0300] {task_command.py:410} INFO - Running <TaskInstance: Investimento_api.Insert_Postgres manual__2023-09-04T13:01:48.178412+00:00 [running]> on host VMEnricolm.myguest.virtualbox.org
[2023-09-04T10:02:16.847-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Investimento_api' AIRFLOW_CTX_TASK_ID='Insert_Postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T13:01:48.178412+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-04T13:01:48.178412+00:00'
[2023-09-04T10:02:16.847-0300] {sql.py:265} INFO - Executing: COPY Apple_table FROM '/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-09-04/data.csv' CSV HEADER;
[2023-09-04T10:02:16.867-0300] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-09-04T10:02:16.888-0300] {logging_mixin.py:150} WARNING - /home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/models/connection.py:372 AirflowProviderDeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2023-09-04T10:02:16.913-0300] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-09-04T10:02:16.930-0300] {sql.py:375} INFO - Running statement: COPY Apple_table FROM '/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-09-04/data.csv' CSV HEADER;, parameters: None
[2023-09-04T10:02:16.931-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 271, in execute
    output = hook.run(
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-09-04/data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-09-04T10:02:16.949-0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=Investimento_api, task_id=Insert_Postgres, execution_date=20230904T130148, start_date=20230904T130216, end_date=20230904T130216
[2023-09-04T10:02:16.962-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task Insert_Postgres (could not open file "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-09-04/data.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 13541)
[2023-09-04T10:02:16.971-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-04T10:02:17.000-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
